[package]
name = "ai-code-reviewer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
lexopt = "0.3.0"
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
