[package]
name = "serde-json-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"

[[test]]
name = "unit"
path = "tests/tests.rs"