[package]
name = "serde-json-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
anyhow = "1.0.86"
tokio = { version = "1.38.1", features = ["full"] }

[[test]]
name = "unit"
path = "tests/tests.rs"