[package]
name = "rsntp-example"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rsntp = "4.0.0"
tokio = { version = "1.39", features = ["full"] }

[[test]]
name = "unit"
path = "tests/tests.rs"