[package]
name = "grep"
version = "0.1.0"
edition = "2021"

[dependencies]
grep-searcher = {version = "0.1.0", path = "../searcher"}
grep-regex = {version = "0.1.0", path = "../regex"}
grep-printer = {version = "0.1.0", path = "../printer"}
grep-matcher = {version = "0.1.0", path = "../matcher"}
