[package]
name = "tokio-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.1", features = ["full"] }
rand = "0.9.0-alpha.1"
futures = "0.3.30"

[[test]]
name = "unit"
path = "tests/tests.rs"