# AI 代码评审工作流
name: AI Code Review
on: [push]        # 合并请求时触发
jobs:
  Code-Review:    # 任务名称
    runs-on: ubuntu-latest    # 定义要运行任务的计算机类型
    steps:
      - name: Download Reviewer   # 先下载二进制的 AI Code Reviewer, 本地在 Linux Mint 编译
        # 这里的 “|” 和 shell 脚本中的 "\" 效果相同，表示作为一个整体执行
        run: |
          curl -LJO https://github.com/kwseeker/rust-template/.github/tools/ai-code-reviewer
      - name: Make executable
        run: chmod +x ai-code-reviewer
      - name: Execute AI Code Reviewer
        run: ./ai-code-reviewer